#!/bin/bash
DEMENSES_DIR=/home/nicohman/chain
pm2 start $DEMENSES_DIR/app.js --name "Dragon"  -- 0
pm2  start   $DEMENSES_DIR/app.js --name "Defiant" -- 1
pm2 start  $DEMENSES_DIR/app.js --name "Dragon's Teeth"  -- 2
pm2 start $DEMENSES_DIR/demenses.js &

